### ISSUE TITLE
Schematic and PCB files are corrupt, will not open in DIPTrace

### ISSUE THREAD

**Issue by FourthDr** [rocketscream/Reflow-Oven-Controller#1]
Schematic and PCB files are corrupt, will not open in DIPTrace.

Tried getting and opening the schematic and the PCB files from github. But DipTrace does not recognize the file format. I am using the latest free version from http://www.driptrace.com. Please fix the files or let me know what application opens them.

**Comment by rocketscream** [comment]
Hi,

Please download the new beta or the latest release candidate (2.2) of Diptrace. We were using the Beta version which was meant for final release of 2.2. So sorry on this.

**Comment by FourthDr** [comment]
Hi:

Thanks for the reply. I was puzzled by the fact that the file header said v2.2 but the newest version was only up to 2.1.x.x. I contacted tech support at diptrace and was told basically that you must be using a beta version.

Regard
