### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pwnforce** [rocketscream/Reflow-Oven-Controller#10]
Hi,
I am working on a research project related to the fuzzing of embedded firmware. Currently, we are generating a benchmark for evaluating the current state-of-the-art fuzzing mechanisms. The aim of this benchmark is to help researchers working on this field to evaluate their developed embedded fuzzers correctly and effectively. The Reflow Oven firmware in this Github repository is really interesting for us to be included in our benchmark.

However, unfortunately, we could not find any license regarding this firmware in the repository. I was wondering if there is any possibility for us to modify, distribute, and use this firmware in our benchmark (for sure, with a reference to your Github repository)?
Thanks.

**Comment by rocketscream** [comment]
Yes sure, you can do whatever you want with the code.
