### ISSUE TITLE
Oven stuck in PREHEAT stage

### ISSUE THREAD

**Issue by mgcrea** [rocketscream/Reflow-Oven-Controller#2]
I just recently bought a reflow shield (v1.80). Got almost exactly the same oven that the one shown in the [wiki](http://www.rocketscream.com/wiki/index.php/Reflow_Controller_Shield_(Arduino_Compatible), but it is running on 220v (EU).

Everything is working fine but it looks like the oven can't get past the initial pre-heat stage, when the thermocouple temp is getting close to 150°C, the oven starts switching ON/OFF (like its max temp target was exactly 150°C & not above). So the temp starts idling around 145°C.

Here are the extract from the logs:

```
Time Setpoint Input Output
130 150.00 134.50 1905.75
131 150.00 135.00 1736.14
132 150.00 135.25 1706.51
133 150.00 135.75 1686.88
134 150.00 137.25 1632.24
135 150.00 138.00 1462.56
136 150.00 138.50 1402.86
137 150.00 138.75 1358.14
138 150.00 139.00 1338.43
139 150.00 140.00 1313.70
140 150.00 140.25 1198.95
141 150.00 141.00 1189.19
142 150.00 142.50 1104.42
143 150.00 142.50 939.61
144 150.00 143.00 969.79
145 150.00 143.25 909.97
146 150.00 143.50 890.14
147 150.00 144.00 865.30
148 150.00 144.75 810.45
149 150.00 144.75 730.58
150 150.00 145.75 745.71
151 150.00 146.50 625.82
152 150.00 146.50 555.91
153 150.00 147.50 570.99
154 150.00 147.50 451.06
155 150.00 147.75 471.12
156 150.00 147.50 441.18
157 150.00 147.50 476.24
158 150.00 147.50 471.30
159 150.00 148.00 471.36
160 150.00 148.50 411.41
161 150.00 148.75 361.45
162 150.00 148.75 341.48
163 150.00 148.50 346.51
164 150.00 148.75 376.55
165 150.00 148.50 341.58
166 150.00 149.25 376.62
167 150.00 149.00 281.64
168 150.00 149.25 326.66
169 150.00 149.50 291.68
170 150.00 149.50 266.69
171 150.00 149.50 271.71
172 150.00 149.25 271.72
173 150.00 149.25 301.74
174 150.00 149.25 296.76
175 150.00 149.00 296.78
176 150.00 148.75 326.80
177 150.00 148.50 351.83
178 150.00 149.00 376.87
179 150.00 148.75 311.89
180 150.00 148.75 351.93
181 150.00 148.25 346.96
182 150.00 148.25 407.00
183 150.00 148.00 397.04
184 150.00 147.75 427.09
185 150.00 147.75 452.15
186 150.00 147.75 447.21
187 150.00 147.50 447.26
188 150.00 147.25 477.33
189 150.00 147.25 502.39
190 150.00 147.00 497.46
191 150.00 147.00 527.54
192 150.00 146.50 522.61
193 150.00 146.50 582.70
194 150.00 146.50 572.79
195 150.00 146.25 572.88
196 150.00 146.00 602.97
197 150.00 146.00 628.07
198 150.00 145.75 623.17
199 150.00 145.75 653.28
200 150.00 146.00 648.38
201 150.00 145.50 618.48
202 150.00 145.50 683.59
203 150.00 145.50 673.71
204 150.00 145.00 673.82
205 150.00 145.25 733.94
206 150.00 145.00 694.06
207 150.00 145.00 729.19
208 150.00 145.00 724.31
209 150.00 144.75 724.44
210 150.00 144.50 754.57
211 150.00 144.50 779.71
212 150.00 144.25 774.84
213 150.00 144.25 804.99
214 150.00 144.25 800.13
215 150.00 144.00 800.28
216 150.00 144.25 830.43
217 150.00 144.00 795.57
218 150.00 144.00 830.72
219 150.00 144.00 825.87
220 150.00 144.00 826.02
```

**Comment by rocketscream** [comment]
You'll need to tweak a little on the PID parameter to suit your oven. Please check your mail!

**Comment by mgcrea** [comment]
Hey @rocketscream! Thanks for the quick answer. I managed to get past the preheat stage after a couple of tries. But it looks like my pre-heat stage is really long. Does the curve below looks good enough to perform reflow? Should I try to better insulate my oven?

![reflow](https://dl.dropboxusercontent.com/u/2310128/reflow.png)

I haven't received a mail yet (olivier [at] mg-crea.com).

Anyway thanks a lot.

**Comment by mgcrea** [comment]
If it can help, here is a picture of my setup:

![reflow-pic](https://dl.dropboxusercontent.com/u/2310128/reflow-pic.jpg)

As you can see, I'm using a steel insulated type-K thermocouple, and I'm trying to make contact with the oven grill.

The heating system (two opposite curved L-shape) looks a bit cheap to me.

**Comment by mgcrea** [comment]
After insulating the glass door with plain aluminium sheets & using the tray instead of the grill:

![reflow](https://dl.dropboxusercontent.com/u/2310128/reflow-c.png)

**Comment by rocketscream** [comment]
Hi,

The mail might be in your spam mail because it was delivered.
Looking at the 1 graph, it seems the oven is having a hard time ramping up. I believe this is due to the single element at the top and bottom. The 2nd graph is awesome and I like it very much. Insulation with aluminium sheets usually helps and compensate the hot air that slip out through the thin gap between the glass door and the oven body.

**Comment by a7hybnj2** [comment]
@mgcrea Hey, I am having this exact issue. Did you ever get it figured out? I changed my:
```
#define PID_KP_PREHEAT 150
#define PID_KI_PREHEAT 0.05
#define PID_KD_PREHEAT 200
```
but I really don't understand how to tweak those numbers to be most optimal. This did fix my problem but I don't want it to be too fast or slow or whatever else it could be.
