### ISSUE TITLE
SSR pin goes high on cooldown.

### ISSUE THREAD

**Issue by a7hybnj2** [rocketscream/Reflow-Oven-Controller#7]
I haven't done much testing yet but right around 100c on the cool down phase I can hear my elements click on for a split second.

**Comment by rocketscream** [comment]
As it approaches the 100 Degree Celsius set point, it will try to maintain it at that temperature as what a PID should. Hence, you can see the SSR tries to kick in to maintain it at 100 Degree Celsius. But, all we want to do for the temperature to cool down to 100, and then turn off the PID.  This is not a bug.
